# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-02 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productId', models.IntegerField()),
                ('productName', models.CharField(max_length=200)),
                ('vendor', models.CharField(blank=True, max_length=50, null=True)),
                ('mrp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('batchNum', models.IntegerField()),
                ('batchDate', models.DateField()),
                ('quantity', models.IntegerField(default=0)),
                ('status', models.IntegerField(choices=[(1, 'Approved'), (2, 'Pending')])),
            ],
        ),
    ]
